#!/usr/bin/env python3
"""
Generate a tiny C source that implements LookupKernelSymbol(addr, &sym_addr)
by extracting text symbols from the linked kernel ELF.

Usage: gen-kernsym.py <elf-path> <out-c-path>

This script expects `x86_64-elf-nm` to be available in PATH.
"""
import sys
import subprocess
import re

if len(sys.argv) != 3:
    print("Usage: gen-kernsym.py <elf> <out.c>")
    sys.exit(2)

elf = sys.argv[1]
outc = sys.argv[2]

try:
    proc = subprocess.run(["x86_64-elf-nm", "-n", elf], capture_output=True, text=True, check=True)
except subprocess.CalledProcessError as e:
    print("Failed to run x86_64-elf-nm:", e)
    sys.exit(1)

lines = proc.stdout.splitlines()

syms = []
for ln in lines:
    # expected format: <addr> <type> <name>
    m = re.match(r"^([0-9a-fA-F]+)\s+([A-Za-z])\s+(\S+)$", ln)
    if not m:
        continue
    addr_hex, typ, name = m.groups()
    # pick text symbols (T or t)
    if typ.upper() != 'T':
        continue
    addr = int(addr_hex, 16)
    # skip local/unnamed symbols
    if name.startswith('.L'):
        continue
    syms.append((addr, name))

if not syms:
    print("No text symbols found in ELF; emitting empty table")

# Emit C file
with open(outc, 'w') as f:
    f.write('/* Generated by tools/gen-kernsym.py */\n')
    f.write('#include <rosval.h>\n')
    f.write('#include <stddef.h>\n')
    f.write('\n')
    f.write('typedef struct { UPTR addr; const CHAR8* name; } KernSym;\n')
    f.write('\n')
    f.write('static const KernSym kernsym_table[] = {\n')
    for addr, name in syms:
        # escape quotes in name
        nm = name.replace('"', '\\"')
        f.write('    { (UPTR)0x%x, (const CHAR8*)"%s" },\n' % (addr, nm))
    f.write('};\n\n')
    f.write('static const size_t kernsym_count = sizeof(kernsym_table)/sizeof(kernsym_table[0]);\n\n')
    f.write('extern "C" const CHAR8* LookupKernelSymbol(UPTR addr, UPTR* sym_addr) {\n')
    f.write('    // Binary-search by address. Return the symbol with the highest addr <= target\n')
    f.write('    if (kernsym_count == 0) { if (sym_addr) *sym_addr = 0; return nullptr; }\n')
    f.write('    // find last symbol <= addr\n')
    f.write('    size_t l = 0, r = kernsym_count;\n')
    f.write('    while (l < r) { size_t m = (l + r) / 2; if ((UPTR)kernsym_table[m].addr <= addr) l = m + 1; else r = m; }\n')
    f.write('    if (l == 0) { if (sym_addr) *sym_addr = 0; return nullptr; }\n')
    f.write('    size_t idx = l - 1;\n')
    f.write('    if (sym_addr) *sym_addr = kernsym_table[idx].addr;\n')
    f.write('    return kernsym_table[idx].name;\n')
    f.write('}\n')

print('Wrote', outc, 'with', len(syms), 'symbols')